// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = FounderSectionSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Keyword field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.keyword
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keyword: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type HomeDocumentDataSlicesSlice = HomeAboutSectionSlice | HeroSectionSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type ServicesDocumentDataSlicesSlice = ServiceBlockSlice;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * keywords field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

export type AllDocumentTypes = AboutDocument | HomeDocument | ServicesDocument;

/**
 * Item in *FounderSection → Default → Primary → socials*
 */
export interface FounderSectionSliceDefaultPrimarySocialsItem {
  /**
   * link field in *FounderSection → Default → Primary → socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.socials[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *FounderSection → Default → Primary → experience one*
 */
export interface FounderSectionSliceDefaultPrimaryExperienceOneItem {
  /**
   * text field in *FounderSection → Default → Primary → experience one*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_one[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *FounderSection → Default → Primary → experience two*
 */
export interface FounderSectionSliceDefaultPrimaryExperienceTwoItem {
  /**
   * text field in *FounderSection → Default → Primary → experience two*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_two[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *FounderSection → Default → Primary → experience three*
 */
export interface FounderSectionSliceDefaultPrimaryExperienceThreeItem {
  /**
   * text field in *FounderSection → Default → Primary → experience three*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_three[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *FounderSection → Default → Primary → skills*
 */
export interface FounderSectionSliceDefaultPrimarySkillsItem {
  /**
   * text field in *FounderSection → Default → Primary → skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.skills[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *FounderSection → Default → Primary*
 */
export interface FounderSectionSliceDefaultPrimary {
  /**
   * section title field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * title field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * image field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * founder text field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.founder_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  founder_text: prismic.KeyTextField;

  /**
   * founder name field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.founder_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  founder_name: prismic.KeyTextField;

  /**
   * socials field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.socials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<
    Simplify<FounderSectionSliceDefaultPrimarySocialsItem>
  >;

  /**
   * experience title field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience_title: prismic.KeyTextField;

  /**
   * experience image field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  experience_image: prismic.ImageField<never>;

  /**
   * experience title one field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_title_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience_title_one: prismic.KeyTextField;

  /**
   * experience title two field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_title_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience_title_two: prismic.KeyTextField;

  /**
   * experience title three field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_title_three
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience_title_three: prismic.KeyTextField;

  /**
   * experience one field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_one[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  experience_one: prismic.GroupField<
    Simplify<FounderSectionSliceDefaultPrimaryExperienceOneItem>
  >;

  /**
   * experience two field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_two[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  experience_two: prismic.GroupField<
    Simplify<FounderSectionSliceDefaultPrimaryExperienceTwoItem>
  >;

  /**
   * experience three field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_three[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  experience_three: prismic.GroupField<
    Simplify<FounderSectionSliceDefaultPrimaryExperienceThreeItem>
  >;

  /**
   * skills field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.skills[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<
    Simplify<FounderSectionSliceDefaultPrimarySkillsItem>
  >;
}

/**
 * Default variation for FounderSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FounderSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FounderSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FounderSection*
 */
type FounderSectionSliceVariation = FounderSectionSliceDefault;

/**
 * FounderSection Shared Slice
 *
 * - **API ID**: `founder_section`
 * - **Description**: FounderSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FounderSectionSlice = prismic.SharedSlice<
  "founder_section",
  FounderSectionSliceVariation
>;

/**
 * Item in *HeroSection → Default → Primary → items*
 */
export interface HeroSectionSliceDefaultPrimaryItemsItem {
  /**
   * image field in *HeroSection → Default → Primary → items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * subtitle field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * link text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * link url field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * image1 field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * items field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<HeroSectionSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *HomeAboutSection → Default → Primary → features*
 */
export interface HomeAboutSectionSliceDefaultPrimaryFeaturesItem {
  /**
   * text field in *HomeAboutSection → Default → Primary → features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.features[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *HomeAboutSection → Default → Primary → logos*
 */
export interface HomeAboutSectionSliceDefaultPrimaryLogosItem {
  /**
   * logo field in *HomeAboutSection → Default → Primary → logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeAboutSection → Default → Primary*
 */
export interface HomeAboutSectionSliceDefaultPrimary {
  /**
   * title field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * features field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<HomeAboutSectionSliceDefaultPrimaryFeaturesItem>
  >;

  /**
   * logo field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * logo one field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.logo_one
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_one: prismic.ImageField<never>;

  /**
   * logo two field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.logo_two
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_two: prismic.ImageField<never>;

  /**
   * logo three field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.logo_three
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_three: prismic.ImageField<never>;

  /**
   * logos field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<
    Simplify<HomeAboutSectionSliceDefaultPrimaryLogosItem>
  >;
}

/**
 * Default variation for HomeAboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeAboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeAboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeAboutSection*
 */
type HomeAboutSectionSliceVariation = HomeAboutSectionSliceDefault;

/**
 * HomeAboutSection Shared Slice
 *
 * - **API ID**: `home_about_section`
 * - **Description**: HomeAboutSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeAboutSectionSlice = prismic.SharedSlice<
  "home_about_section",
  HomeAboutSectionSliceVariation
>;

/**
 * Item in *ServiceBlock → Default → Primary → services*
 */
export interface ServiceBlockSliceDefaultPrimaryServicesItem {
  /**
   * title field in *ServiceBlock → Default → Primary → services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *ServiceBlock → Default → Primary → services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.services[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * image field in *ServiceBlock → Default → Primary → services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.services[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * button link field in *ServiceBlock → Default → Primary → services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.services[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * button text field in *ServiceBlock → Default → Primary → services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.services[].button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Primary content in *ServiceBlock → Default → Primary*
 */
export interface ServiceBlockSliceDefaultPrimary {
  /**
   * title field in *ServiceBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * services field in *ServiceBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<
    Simplify<ServiceBlockSliceDefaultPrimaryServicesItem>
  >;
}

/**
 * Default variation for ServiceBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceBlock*
 */
type ServiceBlockSliceVariation = ServiceBlockSliceDefault;

/**
 * ServiceBlock Shared Slice
 *
 * - **API ID**: `service_block`
 * - **Description**: ServiceBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceBlockSlice = prismic.SharedSlice<
  "service_block",
  ServiceBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      AllDocumentTypes,
      FounderSectionSlice,
      FounderSectionSliceDefaultPrimarySocialsItem,
      FounderSectionSliceDefaultPrimaryExperienceOneItem,
      FounderSectionSliceDefaultPrimaryExperienceTwoItem,
      FounderSectionSliceDefaultPrimaryExperienceThreeItem,
      FounderSectionSliceDefaultPrimarySkillsItem,
      FounderSectionSliceDefaultPrimary,
      FounderSectionSliceVariation,
      FounderSectionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimaryItemsItem,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HomeAboutSectionSlice,
      HomeAboutSectionSliceDefaultPrimaryFeaturesItem,
      HomeAboutSectionSliceDefaultPrimaryLogosItem,
      HomeAboutSectionSliceDefaultPrimary,
      HomeAboutSectionSliceVariation,
      HomeAboutSectionSliceDefault,
      ServiceBlockSlice,
      ServiceBlockSliceDefaultPrimaryServicesItem,
      ServiceBlockSliceDefaultPrimary,
      ServiceBlockSliceVariation,
      ServiceBlockSliceDefault,
    };
  }
}
