// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice =
  | ContactCardSlice
  | HeroBlockSlice
  | ValuesBlockSlice
  | AboutFunnerdBlockSlice
  | FounderSectionSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Keyword field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.keyword
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keyword: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type HomeDocumentDataSlicesSlice =
  | HomeFounderBlockSlice
  | FeaturesBlockSlice
  | ContactCardSlice
  | HomeAboutSectionSlice
  | HeroSectionSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type ServicesDocumentDataSlicesSlice =
  | ServicesHeroBlockSlice
  | ContactCardSlice
  | ServiceBlockSlice;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * keywords field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  keywords: prismic.KeyTextField;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

export type AllDocumentTypes = AboutDocument | HomeDocument | ServicesDocument;

/**
 * Item in *AboutFunnerdBlock → Default → Primary → info*
 */
export interface AboutFunnerdBlockSliceDefaultPrimaryInfoItem {
  /**
   * text field in *AboutFunnerdBlock → Default → Primary → info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_funnerd_block.default.primary.info[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * subtext field in *AboutFunnerdBlock → Default → Primary → info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_funnerd_block.default.primary.info[].subtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtext: prismic.KeyTextField;
}

/**
 * Primary content in *AboutFunnerdBlock → Default → Primary*
 */
export interface AboutFunnerdBlockSliceDefaultPrimary {
  /**
   * image field in *AboutFunnerdBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_funnerd_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *AboutFunnerdBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_funnerd_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *AboutFunnerdBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_funnerd_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * info field in *AboutFunnerdBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_funnerd_block.default.primary.info[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  info: prismic.GroupField<
    Simplify<AboutFunnerdBlockSliceDefaultPrimaryInfoItem>
  >;
}

/**
 * Default variation for AboutFunnerdBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutFunnerdBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutFunnerdBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutFunnerdBlock*
 */
type AboutFunnerdBlockSliceVariation = AboutFunnerdBlockSliceDefault;

/**
 * AboutFunnerdBlock Shared Slice
 *
 * - **API ID**: `about_funnerd_block`
 * - **Description**: AboutFunnerdBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutFunnerdBlockSlice = prismic.SharedSlice<
  "about_funnerd_block",
  AboutFunnerdBlockSliceVariation
>;

/**
 * Item in *ContactCard → Default → Primary → images*
 */
export interface ContactCardSliceDefaultPrimaryImagesItem {
  /**
   * image field in *ContactCard → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_card.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ContactCard → Default → Primary*
 */
export interface ContactCardSliceDefaultPrimary {
  /**
   * images field in *ContactCard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_card.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ContactCardSliceDefaultPrimaryImagesItem>
  >;

  /**
   * content field in *ContactCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_card.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * btn text field in *ContactCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_card.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * btn link field in *ContactCard → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_card.default.primary.btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for ContactCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactCard*
 */
type ContactCardSliceVariation = ContactCardSliceDefault;

/**
 * ContactCard Shared Slice
 *
 * - **API ID**: `contact_card`
 * - **Description**: ContactCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactCardSlice = prismic.SharedSlice<
  "contact_card",
  ContactCardSliceVariation
>;

/**
 * Item in *FeaturesBlock → Default → Primary → features*
 */
export interface FeaturesBlockSliceDefaultPrimaryFeaturesItem {
  /**
   * image field in *FeaturesBlock → Default → Primary → features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features_block.default.primary.features[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *FeaturesBlock → Default → Primary → features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_block.default.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *FeaturesBlock → Default → Primary → features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_block.default.primary.features[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *FeaturesBlock → Default → Primary*
 */
export interface FeaturesBlockSliceDefaultPrimary {
  /**
   * title field in *FeaturesBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * features field in *FeaturesBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: features_block.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<FeaturesBlockSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for FeaturesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturesBlock*
 */
type FeaturesBlockSliceVariation = FeaturesBlockSliceDefault;

/**
 * FeaturesBlock Shared Slice
 *
 * - **API ID**: `features_block`
 * - **Description**: FeaturesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesBlockSlice = prismic.SharedSlice<
  "features_block",
  FeaturesBlockSliceVariation
>;

/**
 * Item in *FounderSection → Default → Primary → socials*
 */
export interface FounderSectionSliceDefaultPrimarySocialsItem {
  /**
   * link field in *FounderSection → Default → Primary → socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.socials[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *FounderSection → Default → Primary → experience one*
 */
export interface FounderSectionSliceDefaultPrimaryExperienceOneItem {
  /**
   * text field in *FounderSection → Default → Primary → experience one*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_one[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *FounderSection → Default → Primary → experience two*
 */
export interface FounderSectionSliceDefaultPrimaryExperienceTwoItem {
  /**
   * text field in *FounderSection → Default → Primary → experience two*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_two[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *FounderSection → Default → Primary → experience three*
 */
export interface FounderSectionSliceDefaultPrimaryExperienceThreeItem {
  /**
   * text field in *FounderSection → Default → Primary → experience three*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_three[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *FounderSection → Default → Primary → skills*
 */
export interface FounderSectionSliceDefaultPrimarySkillsItem {
  /**
   * text field in *FounderSection → Default → Primary → skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.skills[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *FounderSection → Default → Primary*
 */
export interface FounderSectionSliceDefaultPrimary {
  /**
   * section title field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * title field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * image field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * founder text field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.founder_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  founder_text: prismic.KeyTextField;

  /**
   * founder name field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.founder_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  founder_name: prismic.KeyTextField;

  /**
   * socials field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.socials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<
    Simplify<FounderSectionSliceDefaultPrimarySocialsItem>
  >;

  /**
   * experience title field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience_title: prismic.KeyTextField;

  /**
   * experience image field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  experience_image: prismic.ImageField<never>;

  /**
   * experience title one field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_title_one
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience_title_one: prismic.KeyTextField;

  /**
   * experience title two field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_title_two
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience_title_two: prismic.KeyTextField;

  /**
   * experience title three field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_title_three
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience_title_three: prismic.KeyTextField;

  /**
   * experience one field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_one[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  experience_one: prismic.GroupField<
    Simplify<FounderSectionSliceDefaultPrimaryExperienceOneItem>
  >;

  /**
   * experience two field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_two[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  experience_two: prismic.GroupField<
    Simplify<FounderSectionSliceDefaultPrimaryExperienceTwoItem>
  >;

  /**
   * experience three field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.experience_three[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  experience_three: prismic.GroupField<
    Simplify<FounderSectionSliceDefaultPrimaryExperienceThreeItem>
  >;

  /**
   * skills field in *FounderSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: founder_section.default.primary.skills[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<
    Simplify<FounderSectionSliceDefaultPrimarySkillsItem>
  >;
}

/**
 * Default variation for FounderSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FounderSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FounderSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FounderSection*
 */
type FounderSectionSliceVariation = FounderSectionSliceDefault;

/**
 * FounderSection Shared Slice
 *
 * - **API ID**: `founder_section`
 * - **Description**: FounderSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FounderSectionSlice = prismic.SharedSlice<
  "founder_section",
  FounderSectionSliceVariation
>;

/**
 * Item in *HeroBlock → Default → Primary → images*
 */
export interface HeroBlockSliceDefaultPrimaryImagesItem {
  /**
   * image field in *HeroBlock → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_block.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *HeroBlock → Default → Primary*
 */
export interface HeroBlockSliceDefaultPrimary {
  /**
   * title field in *HeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *HeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * btn text field in *HeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_block.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * btn link field in *HeroBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_block.default.primary.btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * images field in *HeroBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_block.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<HeroBlockSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for HeroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBlock*
 */
type HeroBlockSliceVariation = HeroBlockSliceDefault;

/**
 * HeroBlock Shared Slice
 *
 * - **API ID**: `hero_block`
 * - **Description**: HeroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBlockSlice = prismic.SharedSlice<
  "hero_block",
  HeroBlockSliceVariation
>;

/**
 * Item in *HeroSection → Default → Primary → items*
 */
export interface HeroSectionSliceDefaultPrimaryItemsItem {
  /**
   * image field in *HeroSection → Default → Primary → items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *HeroSection → Default → Primary → exams*
 */
export interface HeroSectionSliceDefaultPrimaryExamsItem {
  /**
   * name field in *HeroSection → Default → Primary → exams*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.exams[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * subtitle field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * link text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * link url field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * image1 field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * image2 field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * items field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<HeroSectionSliceDefaultPrimaryItemsItem>>;

  /**
   * brand text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.brand_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  brand_text: prismic.KeyTextField;

  /**
   * exams field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.exams[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  exams: prismic.GroupField<Simplify<HeroSectionSliceDefaultPrimaryExamsItem>>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *HomeAboutSection → Default → Primary → features*
 */
export interface HomeAboutSectionSliceDefaultPrimaryFeaturesItem {
  /**
   * text field in *HomeAboutSection → Default → Primary → features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.features[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *HomeAboutSection → Default → Primary → logos*
 */
export interface HomeAboutSectionSliceDefaultPrimaryLogosItem {
  /**
   * logo field in *HomeAboutSection → Default → Primary → logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *HomeAboutSection → Default → Primary*
 */
export interface HomeAboutSectionSliceDefaultPrimary {
  /**
   * title field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * features field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<HomeAboutSectionSliceDefaultPrimaryFeaturesItem>
  >;

  /**
   * logo field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * logo one field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.logo_one
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_one: prismic.ImageField<never>;

  /**
   * logo two field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.logo_two
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_two: prismic.ImageField<never>;

  /**
   * logo three field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.logo_three
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_three: prismic.ImageField<never>;

  /**
   * logos field in *HomeAboutSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_about_section.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logos: prismic.GroupField<
    Simplify<HomeAboutSectionSliceDefaultPrimaryLogosItem>
  >;
}

/**
 * Default variation for HomeAboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeAboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeAboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeAboutSection*
 */
type HomeAboutSectionSliceVariation = HomeAboutSectionSliceDefault;

/**
 * HomeAboutSection Shared Slice
 *
 * - **API ID**: `home_about_section`
 * - **Description**: HomeAboutSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeAboutSectionSlice = prismic.SharedSlice<
  "home_about_section",
  HomeAboutSectionSliceVariation
>;

/**
 * Primary content in *HomeFounderBlock → Default → Primary*
 */
export interface HomeFounderBlockSliceDefaultPrimary {
  /**
   * image field in *HomeFounderBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_founder_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *HomeFounderBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_founder_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *HomeFounderBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_founder_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * btn link field in *HomeFounderBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_founder_block.default.primary.btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * btn text field in *HomeFounderBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_founder_block.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;
}

/**
 * Default variation for HomeFounderBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeFounderBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeFounderBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeFounderBlock*
 */
type HomeFounderBlockSliceVariation = HomeFounderBlockSliceDefault;

/**
 * HomeFounderBlock Shared Slice
 *
 * - **API ID**: `home_founder_block`
 * - **Description**: HomeFounderBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeFounderBlockSlice = prismic.SharedSlice<
  "home_founder_block",
  HomeFounderBlockSliceVariation
>;

/**
 * Item in *ServiceBlock → Default → Primary → services*
 */
export interface ServiceBlockSliceDefaultPrimaryServicesItem {
  /**
   * title field in *ServiceBlock → Default → Primary → services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *ServiceBlock → Default → Primary → services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.services[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * image field in *ServiceBlock → Default → Primary → services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.services[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * button link field in *ServiceBlock → Default → Primary → services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.services[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * button text field in *ServiceBlock → Default → Primary → services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.services[].button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Primary content in *ServiceBlock → Default → Primary*
 */
export interface ServiceBlockSliceDefaultPrimary {
  /**
   * title field in *ServiceBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * services field in *ServiceBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_block.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<
    Simplify<ServiceBlockSliceDefaultPrimaryServicesItem>
  >;
}

/**
 * Default variation for ServiceBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceBlock*
 */
type ServiceBlockSliceVariation = ServiceBlockSliceDefault;

/**
 * ServiceBlock Shared Slice
 *
 * - **API ID**: `service_block`
 * - **Description**: ServiceBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceBlockSlice = prismic.SharedSlice<
  "service_block",
  ServiceBlockSliceVariation
>;

/**
 * Primary content in *ServicesHeroBlock → Default → Primary*
 */
export interface ServicesHeroBlockSliceDefaultPrimary {
  /**
   * title field in *ServicesHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_hero_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *ServicesHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_hero_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * image one field in *ServicesHeroBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_hero_block.default.primary.image_one
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_one: prismic.ImageField<never>;

  /**
   * image two field in *ServicesHeroBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_hero_block.default.primary.image_two
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_two: prismic.ImageField<never>;

  /**
   * image three field in *ServicesHeroBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_hero_block.default.primary.image_three
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_three: prismic.ImageField<never>;

  /**
   * image four field in *ServicesHeroBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_hero_block.default.primary.image_four
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_four: prismic.ImageField<never>;

  /**
   * btn text field in *ServicesHeroBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_hero_block.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * btn link field in *ServicesHeroBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_hero_block.default.primary.btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for ServicesHeroBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesHeroBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesHeroBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesHeroBlock*
 */
type ServicesHeroBlockSliceVariation = ServicesHeroBlockSliceDefault;

/**
 * ServicesHeroBlock Shared Slice
 *
 * - **API ID**: `services_hero_block`
 * - **Description**: ServicesHeroBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesHeroBlockSlice = prismic.SharedSlice<
  "services_hero_block",
  ServicesHeroBlockSliceVariation
>;

/**
 * Item in *ValuesBlock → Default → Primary → values*
 */
export interface ValuesBlockSliceDefaultPrimaryValuesItem {
  /**
   * title field in *ValuesBlock → Default → Primary → values*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: values_block.default.primary.values[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *ValuesBlock → Default → Primary → values*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: values_block.default.primary.values[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *ValuesBlock → Default → Primary*
 */
export interface ValuesBlockSliceDefaultPrimary {
  /**
   * title field in *ValuesBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: values_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * btn text field in *ValuesBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: values_block.default.primary.btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btn_text: prismic.KeyTextField;

  /**
   * btn link field in *ValuesBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: values_block.default.primary.btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btn_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * values field in *ValuesBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: values_block.default.primary.values[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  values: prismic.GroupField<
    Simplify<ValuesBlockSliceDefaultPrimaryValuesItem>
  >;
}

/**
 * Default variation for ValuesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValuesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ValuesBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ValuesBlock*
 */
type ValuesBlockSliceVariation = ValuesBlockSliceDefault;

/**
 * ValuesBlock Shared Slice
 *
 * - **API ID**: `values_block`
 * - **Description**: ValuesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValuesBlockSlice = prismic.SharedSlice<
  "values_block",
  ValuesBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutFunnerdBlockSlice,
      AboutFunnerdBlockSliceDefaultPrimaryInfoItem,
      AboutFunnerdBlockSliceDefaultPrimary,
      AboutFunnerdBlockSliceVariation,
      AboutFunnerdBlockSliceDefault,
      ContactCardSlice,
      ContactCardSliceDefaultPrimaryImagesItem,
      ContactCardSliceDefaultPrimary,
      ContactCardSliceVariation,
      ContactCardSliceDefault,
      FeaturesBlockSlice,
      FeaturesBlockSliceDefaultPrimaryFeaturesItem,
      FeaturesBlockSliceDefaultPrimary,
      FeaturesBlockSliceVariation,
      FeaturesBlockSliceDefault,
      FounderSectionSlice,
      FounderSectionSliceDefaultPrimarySocialsItem,
      FounderSectionSliceDefaultPrimaryExperienceOneItem,
      FounderSectionSliceDefaultPrimaryExperienceTwoItem,
      FounderSectionSliceDefaultPrimaryExperienceThreeItem,
      FounderSectionSliceDefaultPrimarySkillsItem,
      FounderSectionSliceDefaultPrimary,
      FounderSectionSliceVariation,
      FounderSectionSliceDefault,
      HeroBlockSlice,
      HeroBlockSliceDefaultPrimaryImagesItem,
      HeroBlockSliceDefaultPrimary,
      HeroBlockSliceVariation,
      HeroBlockSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimaryItemsItem,
      HeroSectionSliceDefaultPrimaryExamsItem,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HomeAboutSectionSlice,
      HomeAboutSectionSliceDefaultPrimaryFeaturesItem,
      HomeAboutSectionSliceDefaultPrimaryLogosItem,
      HomeAboutSectionSliceDefaultPrimary,
      HomeAboutSectionSliceVariation,
      HomeAboutSectionSliceDefault,
      HomeFounderBlockSlice,
      HomeFounderBlockSliceDefaultPrimary,
      HomeFounderBlockSliceVariation,
      HomeFounderBlockSliceDefault,
      ServiceBlockSlice,
      ServiceBlockSliceDefaultPrimaryServicesItem,
      ServiceBlockSliceDefaultPrimary,
      ServiceBlockSliceVariation,
      ServiceBlockSliceDefault,
      ServicesHeroBlockSlice,
      ServicesHeroBlockSliceDefaultPrimary,
      ServicesHeroBlockSliceVariation,
      ServicesHeroBlockSliceDefault,
      ValuesBlockSlice,
      ValuesBlockSliceDefaultPrimaryValuesItem,
      ValuesBlockSliceDefaultPrimary,
      ValuesBlockSliceVariation,
      ValuesBlockSliceDefault,
    };
  }
}
