// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_section: dynamic(() => import("./HeroSection")),
  home_about_section: dynamic(() => import("./HomeAboutSection")),
};
